bgs -z ~/.config/h_wallpaper.jpg

[ -z $SSH_AGENT_PID ] && eval $(ssh-agent)
[ $(pgrep gpg-agent) ] || gpg-agent --daemon

[ $(pgrep mpd) ] || mpd
[ $(pgrep cron) ] || cron -f ~/.config/cron/crontab
[ $(pgrep xbanish) ] || xbanish &

[ $(pgrep status) ] || status &
[ $(pgrep mpdidle) ] || mpdidle &

[ -d /tmp/downloads ] || mkdir /tmp/downloads

xset s off -dpms

export $(dbus-launch)

export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx

if [ -f /etc/arch-release ]; then
	/usr/bin/pipewire &
	/usr/bin/pipewire-pulse &
	/usr/bin/wireplumber &
fi

exec ~/bin/dwm
