bgs -z ~/.config/h_wallpaper.jpg

[ -z $SSH_AGENT_PID ] && eval $(ssh-agent)
pidof -s gpg-agent || gpg-agent --daemon

pidof -s cron || cron -f ~/.config/cron/crontab

as="mpd mpdidle status xbanish"
for cmd in $as; do
	pidof -s "$cmd" || "$cmd" &
done >/dev/null 2>&1

xset s off -dpms

[ -d /tmp/downloads ] || mkdir /tmp/downloads

export $(dbus-launch)

export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx

if [ -f /etc/arch-release ]; then
	/usr/bin/pipewire &
	/usr/bin/pipewire-pulse &
	/usr/bin/wireplumber &
fi

exec ~/bin/dwm
